version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

    depends_on:
      - postgres
  postgres:
    image: postgres:10.6
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
