apiVersion: v1
kind: Secret
metadata:
  name: apollo-env
  namespace: notification
  labels:
    app: apollo
type: Opaque
data: 
  client_id: "change me"
  client_secret: "change me"
  MQ_USER: "change me"
  MQ_PASS: "change me"
---
apiVersion: v1
kind: Secret
metadata:
  name: prisma-env
  namespace: notification
  labels:
    app: prismagraphql
type: Opaque
data: 
  PRISMA_CONFIG: |
    port: 4466
    # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
    # managementApiSecret: thehouseisalwaysblue
    databases:
      default:
        connector: postgres
        host: postgres
        port: 5432
        user: prisma
        password: prisma
        migrations: true
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-env
  namespace: notification
  labels:
    app: postgres
type: Opaque
data: 
  POSTGRES_USER: prisma
  POSTGRES_PASSWORD: prisma